config/routes.rb
Rails.application.routes.draw do
  resources :user_movies

  devise_for :users
  resources :movies

  get 'movies/index'

  root 'movies#index'

  get '/search' => 'movies#search'

end

app/models/movie.rb
class Movie < ActiveRecord::Base
	has_many :user_movie

	def index
		@movie = Tmdb::Movie.find(params[:query])
	end

	def self.search(query)
		@movie = Tmdb::Search.new
		@movie.resource('movie') # determines type of resource
		@movie.query(query) # the query to search against
		@movie.fetch # makes request
	end
end

app/models/user.rb
class User < ActiveRecord::Base
	# Include default devise modules. Others available are:
	# :confirmable, :lockable, :timeoutable and :omniauthable
	devise :database_authenticatable, :registerable,
	     :recoverable, :rememberable, :trackable, :validatable
	has_many :user_movie
end

app/models/user_movie.rb
class UserMovie < ActiveRecord::Base
	belongs_to :user
	belongs_to :movie
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
  end

  def search
    @movie = Movie.search(params[:q])
    @configuration = Tmdb::Configuration.new
  end

  def show
  end

end

app/controllers/user_movies_controller.rb
class UserMoviesController < ApplicationController
  before_action :set_user_movie, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @user_movies = UserMovie.all
    respond_with(@user_movies)
  end

  def show
    respond_with(@user_movie)
  end

  def new
    @user_movie = UserMovie.new
    respond_with(@user_movie)
  end

  def edit
  end

  def create
    @user_movie = UserMovie.new(user_movie_params)
    @user_movie.save
    respond_with(@user_movie)
  end

  def update
    @user_movie.update(user_movie_params)
    respond_with(@user_movie)
  end

  def destroy
    @user_movie.destroy
    respond_with(@user_movie)
  end

  private
    def set_user_movie
      @user_movie = UserMovie.find(params[:id])
    end

    def user_movie_params
      params.require(:user_movie).permit(:user_id, :movie_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/user_movies_helper.rb
module UserMoviesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RubyApp2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<p class="navbar-text pull-right">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>

<%= yield %>
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

</body>
</html>

app/views/movies/index.html.erb
<h1>Movies#index</h1>
<p>Find me in app/views/movies/index.html.erb</p>

<%= form_tag('/search', method: "get") do %>
  <p><%= text_field_tag(:q) %></p>
  <div><%= submit_tag('search') %></div>
<% end %>

app/views/movies/search.html.erb
<% if user_signed_in? %>
User id: <%= current_user.id %>

<h1>Listing Movie</h1>
  
<table>
  <thead>
    <tr>
      <th>image</th>
      <th>title</th>
      <th>Movie id</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @movie.each do |mov| %>
      <tr>
        <td><%= image_tag("#{@configuration.base_url}w154#{mov['poster_path']}") if mov["poster_path"] %></td>
        <td><%= mov["title"] %></td>
        <td><%= mov["id"] %></td>
        <td>
          <%= link_to "Add to my list", new_user_movie_path(:user_id => current_user.id, :movie_id => mov["id"]) %> </td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

<% end %>

app/views/movies/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @movie.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @movie.description %>
</p>

app/views/user_movies/_form.html.erb
<%= form_for(@user_movie) do |f| %>
  <% if @user_movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_movie.errors.count, "error") %> prohibited this user_movie from being saved:</h2>

      <ul>
      <% @user_movie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :movie_id %><br>
    <%= f.number_field :movie_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_movies/edit.html.erb
<h1>Editing user_movie</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_movie %> |
<%= link_to 'Back', user_movies_path %>

app/views/user_movies/index.html.erb
<h1>Listing user_movies</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Movie</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_movies.each do |user_movie| %>
      <tr>
        <td><%= user_movie.user_id %></td>
        <td><%= user_movie.movie_id %></td>
        <td><%= link_to 'Show', user_movie %></td>
        <td><%= link_to 'Edit', edit_user_movie_path(user_movie) %></td>
        <td><%= link_to 'Destroy', user_movie, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User movie', new_user_movie_path %>

app/views/user_movies/new.html.erb
<h1>New user_movie</h1>

<%= render 'form' %>

<%= link_to 'Back', user_movies_path %>

app/views/user_movies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @user_movie.user_id %>
</p>

<p>
  <strong>Movie:</strong>
  <%= @user_movie.movie_id %>
</p>

<%= link_to 'Edit', edit_user_movie_path(@user_movie) %> |
<%= link_to 'Back', user_movies_path %>